### ISSUE TITLE
dataAnaly.py

### ISSUE THREAD

**Issue by DyerLee** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#1]

**Comment by DyerLee** [comment]
你好，打扰了。请问dataAnaly.py文件执行完是什么结果？

**Comment by junqiangchen** [comment]
> 你好，打扰了。请问dataAnaly.py文件执行完是什么结果？

你好，dataAnaly.py是用来分析原始luna16的数据集的，可以用来设置合适的窗宽窗位和Spacing插值的信息。

**Comment by DyerLee** [comment]
那这个代码执行完以后生成文件吗？打扰发自我的华为手机-------- 原始邮件 --------主题：Re: [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge] dataAnaly.py (#1)发件人：junqiangchen 收件人：junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge 抄送：DyerLee ,Author 

你好，打扰了。请问dataAnaly.py文件执行完是什么结果？



你好，dataAnaly.py是用来分析原始luna16的数据集的，可以用来设置合适的窗宽窗位和Spacing插值的信息。

**Comment by DyerLee** [comment]
你好，打扰了。data分析程序我跑了得有一天了，是不是不对啊？这个程序输出结果是啥。谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge] dataAnaly.py (#1)发件人：junqiangchen 收件人：junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge 抄送：DyerLee ,Author 

你好，打扰了。请问dataAnaly.py文件执行完是什么结果？



你好，dataAnaly.py是用来分析原始luna16的数据集的，可以用来设置合适的窗宽窗位和Spacing插值的信息。
