### ISSUE TITLE
假阳性减少

### ISSUE THREAD

**Issue by chenyafang** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#11]
您好，我之前用luna16数据集已经进行了肺结节的检测，检测结果是假阳性高，想用您的假阳性减少这一模块来去假阳。我看到ResNet3d_train.py这代码里面涉及到nodel_all_train.csv这一文件，但是我没有找到这一文件。请问是不能直接用去假阳这一模块吗？还是有什么解决办法呢？谢谢，祝好！

**Comment by junqiangchen** [comment]
ResNet3d是用来训练分类网络的，这个文件需要生成的，训练好了之后就可以直接用来去除假阳性。
