### ISSUE TITLE
预测结果拼接

### ISSUE THREAD

**Issue by isihkr** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#12]
请问在得到预测结果后，可以如何根据步长等参数对预测图片拼接成512*512的图片？
谢谢！ @junqiangchen

**Comment by junqiangchen** [comment]
> 请问在得到预测结果后，可以如何根据步长等参数对预测图片拼接成512*512的图片？
> 谢谢！ @junqiangchen

预测的时候可以直接512x512大小直接输入预测

**Comment by isihkr** [comment]
谢谢！我试试

**Comment by isihkr** [comment]
你好 我看见您在肝肿瘤分割那个repo中以动画的形式呈现分割结果。主要是以步长为16，不断获取512*512*32的图像，最后您提到需要对分割结果进行拼接合并得到最终结果。我也想以这种方式来呈现识别效果，请问最后一步的拼接合并涉及到何种算法，需要如何实现？谢谢

**Comment by junqiangchen** [comment]
> 你好 我看见您在肝肿瘤分割那个repo中以动画的形式呈现分割结果。主要是以步长为16，不断获取512_512_32的图像，最后您提到需要对分割结果进行拼接合并得到最终结果。我也想以这种方式来呈现识别效果，请问最后一步的拼接合并涉及到何种算法，需要如何实现？谢谢

这个过程其实很简单，就是逐步拼接，最后在图像上绘制轮廓
