### ISSUE TITLE
ValueError: cannot reshape array of size 16 into shape (16,96,96)

### ISSUE THREAD

**Issue by a56256324** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#13]
您好，在使用您提供的模型做segmeation预测时，产生了ValueError: cannot reshape array of size 16 into shape (16,96,96)问题，想请教您如何解决

**Comment by junqiangchen** [comment]
> 您好，在使用您提供的模型做segmeation预测时，产生了ValueError: cannot reshape array of size 16 into shape (16,96,96)问题，想请教您如何解决

你可以调试一下，看看是不是输入的图像大小不对
