### ISSUE TITLE
Vnet模型训练的问题

### ISSUE THREAD

**Issue by Alonelover** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#14]
你好，我是一个初学者。在复现您的代码的时候，出现了一些问题，在训练Vnet模型时训练时间很短就结束了，Training_loss为-0.07308,请问可以给我一些建议吗。 还有一个疑问为什么要令Training_accuracy=-training_loss

**Comment by junqiangchen** [comment]
你好，你这个训练应该没有训练好，训练精度也可以选择其他评价指标。
