### ISSUE TITLE
关于模型检测的问题

### ISSUE THREAD

**Issue by yukkii01** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#16]
我发现，如果我用全黑或者全白的图片放入您的V-net中进行检测，结果却显示有结节，这显然是不科学的，但我并不知道有什么问题，不知道您有尝试过吗？

**Comment by junqiangchen** [comment]
这个我倒是没有尝试过，不过这个问题也是会出现的，因为全黑全白的数据，网络是没有学习过的，所以输入时这种类型的时候，网络也不知道会输出什么结果出来。

**Comment by yukkii01** [comment]
谢谢您的回答，其实我觉得是这个网络的训练集取的过于正确了，您的代码里实际上训练集大部分都是正样本，所以它无法识别这种极端情况

**Comment by junqiangchen** [comment]
是的，训练数据中都是会存在肺结节的，如果没有的话，网络可能学习的不够好。
