### ISSUE TITLE
Prediction result

### ISSUE THREAD

**Issue by cuongnc220592** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#21]
I have trained your models. The results are good by your way.
But when I tested on dataset without segmentation techniques. The results for nodule class(label = 1) is very poor.
Do you think about it ? the test set should not be augmented.

I also want to download your trained models, but it is impossible with foreigners.
Why you do not upload on github ??

Thank you very much

**Comment by junqiangchen** [comment]
hi，
the model has 100M，upload it on github is difficult for me.
the nodule classify make sure the classification balance,so i augmented the nodule data(label 1),and seperate data into trained data and test data.

**Comment by amina2213** [comment]
Hi, 
but how can seperate data into trained and test data ??

Thanks.
