### ISSUE TITLE
data3dprepare.py

### ISSUE THREAD

**Issue by GuobinZhangTJU** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#26]
师兄您好，请问您运行data3dprepare.py共花了多长时间呀？我按您的代码，运行3天了，最后崩在了第154-179个生成文件上面~是不是我是不是哪里出了问题呀？暂时没改变您在data3dprepare.py里面写的参数~

**Comment by GuobinZhangTJU** [comment]
就是data3dprepare.py中的 “samples, imagez = np.shape(sub_srcimages)[0], np.shape(sub_srcimages)[1]“ 中的samples有能达到2900的情况~

**Comment by junqiangchen** [comment]
这个程序我也不记得多长时间，如果出现崩溃错误的话，可以适当改一下patch参数： prepare3dtraindata(srcpath, maskpath, trainImage, trainMask, number, height, width, (16, 96, 96), 10, 16)改成 prepare3dtraindata(srcpath, maskpath, trainImage, trainMask, number, height, width, (64, 96, 96), 10, 32)，如果你的GPU是1080TI以上的话。
