### ISSUE TITLE
Ensembling both models for inference

### ISSUE THREAD

**Issue by paul-fg** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#28]
Hello,

Thanks for sharing your work. Are the 2 models meant to ensemble, chain or otherwise combine in some way? I am wondering how you use the Resnet to reduce FP in the Vnet mask output. Thanks!

**Comment by junqiangchen** [comment]
there is not ensembling the detetion and reduction models,you should do it by yourself.
