### ISSUE TITLE
Citation missing!

### ISSUE THREAD

**Issue by MjdMahasneh** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#30]
Hello, it would be helpful if the paper presenting the work in this repo be cited here for reference.

Any elaboration would be much appreciated :) thanks in advance.

**Comment by junqiangchen** [comment]
sorry,there is not pubilshed paper,but you can follow my wechart public account,there are many articles.

**Comment by MjdMahasneh** [comment]
@junqiangchen Thank you for getting back to me. Could you please provide any type of documentation for this repo? 

For example, the masks in the readme file look like they were somehow converted to square shaped masks! I am not sure why was that done!

Could you kindly provide a short step-by-step description of the pipeline? This would really elevate the quality of this repo and help other to re-use it.

Many thanks in advance.

**Comment by junqiangchen** [comment]
> @junqiangchen Thank you for getting back to me. Could you please provide any type of documentation for this repo?
> 
> For example, the masks in the readme file look like they were somehow converted to square shaped masks! I am not sure why was that done!
> 
> Could you kindly provide a short step-by-step description of the pipeline? This would really elevate the quality of this repo and help other to re-use it.
> 
> Many thanks in advance.

the How to use part is simply introduce how to use the repo.First,convert csv file to mask image file;Second,prepare detection and classify tasks trained data;Third,trained the nets.
thank you

**Comment by MjdMahasneh** [comment]
Thank you for your response.
