### ISSUE TITLE
Mis-matching Total number of candidates

### ISSUE THREAD

**Issue by MjdMahasneh** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#32]
Hello,

after evaluating the predictions file (i.e. METU_VISION_FPRED.csv) using the LUNA16 official script (i.e. noduleCADEvaluationLUNA16.py), I get an output (CADAnalysis.txt) like this :

CADAnalysis.txt

CAD Analysis: METU_VISION_FPRED

Candidate detection results:
True positives: 1128
False positives: 81706
False negatives: 58
True negatives: 0
Total number of candidates: 87794
Total number of nodules: 1186
Ignored candidates on excluded nodules: 4600
Ignored candidates which were double detections on a nodule: 360
Sensitivity: 0.951096121
Average number of candidates per scan: 98.867117117

From what I understand, the the Total number of candidates should be 754,975 according to https://luna16.grand-challenge.org/Evaluation/

Even though METU_VISION_FPRED.csv has 754,975 candidates!! the CADAnalysis.txt still says Total number of candidates: 87794 !!!!!

Looking forward to hearing back from you. Any help is extremely appreciated.

Many thanks.

Any idea why that happens?? Am I missing something?

**Comment by junqiangchen** [comment]
> Hello,
> 
> after evaluating the predictions file (i.e. METU_VISION_FPRED.csv) using the LUNA16 official script (i.e. noduleCADEvaluationLUNA16.py), I get an output (CADAnalysis.txt) like this :
> 
> CADAnalysis.txt
> 
> CAD Analysis: METU_VISION_FPRED
> 
> Candidate detection results:
> True positives: 1128
> False positives: 81706
> False negatives: 58
> True negatives: 0
> Total number of candidates: 87794
> Total number of nodules: 1186
> Ignored candidates on excluded nodules: 4600
> Ignored candidates which were double detections on a nodule: 360
> Sensitivity: 0.951096121
> Average number of candidates per scan: 98.867117117
> 
> From what I understand, the the Total number of candidates should be 754,975 according to https://luna16.grand-challenge.org/Evaluation/
> 
> Even though METU_VISION_FPRED.csv has 754,975 candidates!! the CADAnalysis.txt still says Total number of candidates: 87794 !!!!!
> 
> Looking forward to hearing back from you. Any help is extremely appreciated.
> 
> Many thanks.
> 
> Any idea why that happens?? Am I missing something?

hi,thank you for replying detail message,but i don't known how to explain it.
