### ISSUE TITLE
about the dataprcessing 

### ISSUE THREAD

**Issue by daihahaha** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#33]
陈老师，你好
          我运行数据预处理部分的LUNA_node_extraction.py时，本来应该是生成classification文件夹的，但是我运行后没有结果。调试了一下代码发现line 93处的 if mini_df.shape[0] > 0: 这个判断都没有进去。尝试在此之前添加了一句print（mini_df.shape[0]），发现全部都是零。
          多谢老师指教

**Comment by junqiangchen** [comment]
你好，
要确定所用csv数据和luna16图像数据是正确的。代码应该是没问题的。
谢谢

**Comment by daihahaha** [comment]
好的 谢谢陈老师，我再仔细核对一下



发自我的iPhone


------------------ Original ------------------

**Comment by zhang-qiang-github** [comment]
@daihahaha 应该是df_node[df_node["file"] == img_file]这句话有错吧，我改了一下：
df_node[df_node["file"] == img_file[0:-4]]
你可以调试一下，看看df_node里面到底路径是啥，要不要加上mhd之类的

**Comment by Liuxinyu-ayu** [comment]
for fcount, img_file in enumerate(tqdm(**file_list_path**)):
是这里的问题，原代码写的是file_list，里面带有了.mhd，所以匹配不上
