### ISSUE TITLE
How to test a complete 3D image?

### ISSUE THREAD

**Issue by zhang-qiang-github** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#34]
I want to know how can we test a complete 3D image? If I have a 3D image (512*512*300), how to generate the nodule? Is there a such test code?
In addition, how to generate the confusion matrix and metrics?

**Comment by junqiangchen** [comment]
> I want to know how can we test a complete 3D image? If I have a 3D image (512_512_300), how to generate the nodule? Is there a such test code?
> In addition, how to generate the confusion matrix and metrics?

hi，you can input 3D image to detect net,and output the nodules roi,then input to classify net.
confusion matric and metrics can find on sklearn library.

**Comment by phzbbbbbbbb** [comment]
> 

你好，请问detect net在哪个部分

**Comment by perhapzz** [comment]
> > I want to know how can we test a complete 3D image? If I have a 3D image (512_512_300), how to generate the nodule? Is there a such test code?
> > In addition, how to generate the confusion matrix and metrics?
> 
> hi，you can input 3D image to detect net,and output the nodules roi,then input to classify net. confusion matric and metrics can find on sklearn library.

你好，请问detect net在哪个部分
