### ISSUE TITLE
Coordinate Transformation Problem

### ISSUE THREAD

**Issue by shao1720707213** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#35]
In the ‘candidates.csv’, why is it that the nodule coordinates minus the origin coordinates get negative?

**Comment by junqiangchen** [comment]
hi,when convert nodule world coord into image coord,you can use this fucntion of simpleitk,transformphysicaltoindex() to get nodule image coord.thank you

**Comment by junqiangchen** [comment]
> In the ‘candidates.csv’, why is it that the nodule coordinates minus the origin coordinates get negative?

hi,when convert nodule world coord into image coord,you can use this fucntion of simpleitk,transformphysicaltoindex() to get nodule image coord.thank you

**Comment by shao1720707213** [comment]
Thank you very much for your answer. I will try it.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: junqiangchen<mailto:notifications@github.com>
发送时间: 2020年11月30日 12:56
收件人: junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge<mailto:LUNA16-Lung-Nodule-Analysis-2016-Challenge@noreply.github.com>
抄送: shao1720707213<mailto:shao.yanbo@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge] Coordinate Transformation Problem (#35)


In the ‘candidates.csv’, why is it that the nodule coordinates minus the origin coordinates get negative?

hi,when convert nodule world coord into image coord,you can use this fucntion of simpleitk,transformphysicaltoindex() to get nodule image coord.thank you

―
