### ISSUE TITLE
Augmain.py file is not executing

### ISSUE THREAD

**Issue by NuthanakantiBhaskar** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#36]
Dear Sir, your work is helped me a lot in that I'm facing following problem,
please suggest how to run Augmain.py in spyder. when I run it showing following error:

  File "D:\mywork\LUNA16 Master\Augmain.py", line 1, in <module>
    from dataaugmentation.Augmentation.ImageAugmentation import DataAug3D

ModuleNotFoundError: No module named 'dataaugmentation'

So, please provide the solution for above problem.

thank for advance

**Comment by junqiangchen** [comment]
> Dear Sir, your work is helped me a lot in that I'm facing following problem,
> please suggest how to run Augmain.py in spyder. when I run it showing following error:
> 
> File "D:\mywork\LUNA16 Master\Augmain.py", line 1, in
> from dataaugmentation.Augmentation.ImageAugmentation import DataAug3D
> 
> ModuleNotFoundError: No module named 'dataaugmentation'
> 
> So, please provide the solution for above problem.
> 
> thank for advance

you can try on pycharm

**Comment by nuje98** [comment]
@NuthanakantiBhaskar 
Try this : 
from Augmentation.ImageAugmentation import DataAug3D
Instead of this :
from dataaugmentation.Augmentation.ImageAugmentation import DataAug3D
