### ISSUE TITLE
关于data3dprepare

### ISSUE THREAD

**Issue by JunX1e** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#39]
你好，正在学习相关内容，想问一下data3dprepare是如何获取(96,96,16)的patch的训练数据的
该模型是否可以在原图而不是子图预测出mask

**Comment by junqiangchen** [comment]
在原图中裁切patch可以参考代码实现，有两种方式按照固定步长或随机裁切来获取（96，96，16）的区域出来。

**Comment by junqiangchen** [comment]
> 你好，正在学习相关内容，想问一下data3dprepare是如何获取(96,96,16)的patch的训练数据的
> 该模型是否可以在原图而不是子图预测出mask

在原图上可以进行预测，不过会出现很多假阳目标会被检测出来。
