### ISSUE TITLE
运行的几点疑惑

### ISSUE THREAD

**Issue by GaoShanwen** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#4]
## 我想将其转为pytorch来实现，如果你感觉有什么建议或者要注意的，希望可以指教一下，拜谢！

**Comment by GaoShanwen** [comment]
### @junqiangchen 你好，之前写的不是太完善，我再重新表述一下，不便之处还请见谅：
1、进行分类网络测试的话，是不是只用执行处理中的5~9部分，
2、仅用cpu需要修改工程内容吗？可以的话还请指出环境要求（主要是tensorflow的版本）
### 如另有建议一定认真听取，希望得到回复，感谢！

**Comment by junqiangchen** [comment]
> ## 你好，看过工程的readme，有几点疑惑希望能够得到解答；
> ### 1、中看过处理的9个步骤，我的理解是1～4重新生成了一次图片的掩膜文件和mhd中的坐标、和尺寸信息，根据luna官方给的数据是不是5～9才是必要的？
> ### 2、工程需要的tensorflow是那个版本，仅用GPU可以跑吗？
> ## 我想将其转为pytorch来实现，如果你感觉有什么建议或者要注意的，希望可以指教一下，拜谢！

1、preocess部分是前面1-4是结节检测处理的过程，5-9是分类处理的过程。
2、我用的是tensorflow1.0 GPU的版本。
3、我一直用的是tf，如若要转pytorch，可以参考以下其他资料自己转一下。
谢谢。

**Comment by GaoShanwen** [comment]
### 额，是我该谢谢你，解答了我的主要疑惑。
