### ISSUE TITLE
请问用作结节分割的mask的生成中是否是正负样本均有的

### ISSUE THREAD

**Issue by anjingzyj** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#40]
我运行完程序，把您生成的bmp文件改为生成png图片，查看生成的结节mask，大约每个文件夹有一半是纯黑色图片，是有些是负样本吗

**Comment by junqiangchen** [comment]
切出来的图像中，背景和结节目标都是有的，可以理解背景就是负样本，结节是正样本
