### ISSUE TITLE
良恶性分类

### ISSUE THREAD

**Issue by kingjames1155** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#47]
您好，我阅读了您的文章并尝试了分类相关的程序，您提到的良恶性分类，然后实际上 0 代表非结节， 1 代表结节， 没有良恶性相关的区分，我有点困惑您提到的良恶性分类是如何做到的

**Comment by kyjyya** [comment]
您好，关于分类的部分，请问当我运行了第一个代码后怎么产生不了所谓的0和1文件夹？该怎么解决？

**Comment by junqiangchen** [comment]
@kingjames1155 LUNA16上只有真假阳性分类判断，如果要进一步对结节进行分类可以参考这个数据[https://zenodo.org/record/6559584#.YvH1KCdBxD8](url)，更多信息可以关注微信公众号里面的文章：LUNA2022——肺结节良恶性和类型分析挑战赛

**Comment by MarielMa** [comment]
> @kingjames1155 LUNA16上只有真假阳性分类判断，如果要进一步对结节进行分类可以参考这个数据[https://zenodo.org/record/6559584#.YvH1KCdBxD8](url)，更多信息可以关注微信公众号里面的文章：LUNA2022——肺结节良恶性和类型分析挑战赛

这个数据的结节坐标是不是整个图像的坐标呀？结节怎么提取不出来呢
