### ISSUE TITLE
良恶性分类

### ISSUE THREAD

**Issue by kyjyya** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#48]
您好，感谢您的代码！但在运行分类代码的过程中遇到了无法生成分类文件0和1的问题，请问怎么解决？万分感激。

**Comment by Itachiiiiiiiiiiiiiiii** [comment]
@kyjyya 请问你解决了吗？

**Comment by Candice-Y** [comment]
> 您好，感谢您的代码！但在运行分类代码的过程中遇到了无法生成分类文件0和1的问题，请问怎么解决？万分感激。

您好，我也遇到了同样的问题，请问您解决了吗？如果可以，能分享一下解决方式吗？

**Comment by junqiangchen** [comment]
运行dataprocess里面的LUNA_node_extraction.py就可以生成0和1目录下的npy文件的
