### ISSUE TITLE
module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by MhdAliHarmalani** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#49]
When I am using this method:
Vnet3d = Vnet3dModule(128, 128, 16, channels=1, costname=("dice coefficient",), inference=True,
                          model_path="/content/drive/MyDrive/model/resnet.pd-50000.data-00000-of-00001")

I got this error:

in __init__(self, image_height, image_width, image_depth, channels, costname, inference, model_path)
    195         self.channels = channels
    196 
--> 197         self.X = tf.placeholder("float", shape=[None, self.image_depth, self.image_height, self.image_width,
    198                                                 self.channels])
    199         self.Y_gt = tf.placeholder("float", shape=[None, self.image_depth, self.image_height, self.image_width,

AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by junqiangchen** [comment]
@MhdAliHarmalani the tensorflow version is 1.14,you can try pytorch version from here [https://github.com/junqiangchen/PytorchDeepLearing](url)
