### ISSUE TITLE
subset.py的一些疑惑？

### ISSUE THREAD

**Issue by jieshaoxxiansen** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#5]
您好！正在复现您项目的分类部分，遇到了点问题，不是很理解subset.py文件的运行机理，
具体是里面的sys.argv[1]所对应的文件是什么？望解惑！感谢

**Comment by junqiangchen** [comment]
> 您好！正在复现您项目的分类部分，遇到了点问题，不是很理解subset.py文件的运行机理，
> 具体是里面的sys.argv[1]所对应的文件是什么？望解惑！感谢

 subset.py里面有 readme 文档，有详细使用说明。
