### ISSUE TITLE
良恶 trainloss不下降

### ISSUE THREAD

**Issue by huangguoqing1111** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#52]
你好，我按照你的代码执行良恶数据处理后训练后loss一直在0.5-0.6几震荡，增加了epoch和BN层以及去除数据增强都没有作用，请问你在LUNA2022中得到的训练结果图是执行的这个代码吗？

**Comment by junqiangchen** [comment]
@huangguoqing1111 请参考这个项目https://github.com/junqiangchen/PytorchDeepLearing
