### ISSUE TITLE
结节假阳性二分类数据划分

### ISSUE THREAD

**Issue by sst-LoveStudy** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#53]
请问在肺结节假阳性二分类的时候，代码结果是采用的了全部的结节数据集吗？因为我看到这个任务的正样本有1300+而负样本有5'000'000+

**Comment by junqiangchen** [comment]
@sst-LoveStudy 正样本使用全部，负样本使用部分数据
