### ISSUE TITLE
 How to run Step 4

### ISSUE THREAD

**Issue by a56256324** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#6]
Hello, when you run your program, you encounter some doubts. When I finished running Parts 1-3, I encountered difficulties in running Part 4. I don't know how to save the generated mask to the CSV file. Do you need to write your own code, or which Python file do you want to run? I hope to get your help.
 Thank you.

**Comment by junqiangchen** [comment]
i have shared the csv in the project,you can write the code by yourself,it's not difficult.

**Comment by a56256324** [comment]
Thank you very much. I have found it. I wish you all the best.
