### ISSUE TITLE
测试结果的计算

### ISSUE THREAD

**Issue by GaoShanwen** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#7]
### 很抱歉，再次打扰一下，想问一下工程里有关于测试结果统计的脚本吗？比如工程中的这个
![Confusion_Matrix](https://user-images.githubusercontent.com/40156715/55695380-fd653b00-59ea-11e9-8810-9e44fce725c6.PNG)

**Comment by junqiangchen** [comment]
> ### 很抱歉，再次打扰一下，想问一下工程里有关于测试结果统计的脚本吗？比如工程中的这个
> ![Confusion_Matrix](https://user-images.githubusercontent.com/40156715/55695380-fd653b00-59ea-11e9-8810-9e44fce725c6.PNG)

详见classify_metrics.py文件
