### ISSUE TITLE
请问第四步中segmentation文件夹是如何获取的

### ISSUE THREAD

**Issue by yukkii01** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#8]
您好，在第四步遇到了一些疑惑想向您请教。1-3步顺利得到process文件夹，4看了您分享的已完成的csv文件内的路径，但我不知道如何获取segmentation文件夹，谢谢，祝好。

**Comment by yukkii01** [comment]
我想可能4，5步的顺序反了，不知道我的想法是否正确。

**Comment by GaoShanwen** [comment]
#6 中可能已经回答过这个问题了，你可以看一下

**Comment by yukkii01** [comment]
谢谢您的评论，#6的评论我之前已看过。我目前是通过step5的data3dprepare.py得到segmentation然后再通过utils.py得到step4的csv，不知道我这样理解是否正确，祝好。

**Comment by junqiangchen** [comment]
> 谢谢您的评论，#6的评论我之前已看过。我目前是通过step5的data3dprepare.py得到segmentation然后再通过utils.py得到step4的csv，不知道我这样理解是否正确，祝好。

是的，你很仔细，我会把顺序更改一下
