### ISSUE TITLE
执行了3、4天的epoch是5吗？

### ISSUE THREAD

**Issue by GaoShanwen** [junqiangchen/LUNA16-Lung-Nodule-Analysis-2016-Challenge#9]
抱歉，又来打扰了，我可能对工程做了点修改，根据现在的情况，感觉单卡训练5个epoch要3、4天；

因为5个epoch确实比着其他工程确实太少了，不太确定是不是我的修改有问题，下图（工程里的loss曲线时间是4天）的时间就是执行了5个epoch的时间吗？
![lossDownload](https://user-images.githubusercontent.com/40156715/56112039-7127ba80-5f8c-11e9-8ee1-fccd6c5d59f6.PNG)

**Comment by junqiangchen** [comment]
> 抱歉，又来打扰了，我可能对工程做了点修改，根据现在的情况，感觉单卡训练5个epoch要3、4天；
> 
> 因为5个epoch确实比着其他工程确实太少了，不太确定是不是我的修改有问题，下图（工程里的loss曲线时间是4天）的时间就是执行了5个epoch的时间吗？
> ![lossDownload](https://user-images.githubusercontent.com/40156715/56112039-7127ba80-5f8c-11e9-8ee1-fccd6c5d59f6.PNG)

你好，具体时间我也没有太在意，看着这个loss图好像是花了四天多一点。因为batchsize大小我记得是32，而且数据量还是相对比较大的，如果是单卡训练时间肯定是蛮久的。

**Comment by GaoShanwen** [comment]
你好，感谢你的回复，
数据量大确实有利有弊，5个epoch能训成这样也算可以了，久点就久点吧
